// Regenera supabase/schema_full.sql desde la DB DEV — SIN Docker, SIN pg_dump.
//
// Por qué existe: `supabase db dump` exige Docker (baja la imagen de postgres para usar pg_dump).
// Además, desde algunos entornos NO hay conexión wire-protocol a la DB (el pooler de DEV rechaza la
// auth por el bug de Supavisor y la conexión directa es IPv6-only sin egress). Por eso este script
// tiene DOS modos y elige el que funcione:
//
//   MODO API  (preferido, sólo IPv4/HTTPS): usa la Management API de Supabase
//             POST /v1/projects/{ref}/database/query. Requiere un token:
//               $env:SUPABASE_ACCESS_TOKEN = "sbp_..."   (PAT de supabase.com/dashboard/account/tokens)
//
//   MODO PG   (fallback): conecta al pooler (o directo con --direct) con SUPABASE_DB_PASSWORD.
//             Hoy bloqueado en la PC de GO (Supavisor + sin IPv6), pero sirve desde CI u otra red.
//
// Uso:  npm run schema:dump                         (auto: API si hay token, si no PG)
//       node scripts/dump-schema.mjs --direct       (fuerza conexión directa IPv6)
//       node scripts/dump-schema.mjs --ref <ref>    (otro proyecto; default DEV)
//
// NO es un pg_dump byte-a-byte: es un snapshot fiel y legible del esquema `public` vigente.
import pg from 'pg'
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { resolve6 } from 'node:dns/promises'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = resolve(root, 'supabase/schema_full.sql')

const argv = process.argv.slice(2)
const arg = (k, def) => { const i = argv.indexOf(k); return i >= 0 ? argv[i + 1] : def }
const REF = arg('--ref', 'gcmhzdedrkmmzfzfveig')            // DEV
const DIRECT = argv.includes('--direct')

function envVal(key) {
  try {
    const m = readFileSync(resolve(root, '.env.local'), 'utf8').match(new RegExp('^' + key + '=(.*)$', 'm'))
    return m ? m[1].trim() : undefined
  } catch { return undefined }
}
const TOKEN = process.env.SUPABASE_ACCESS_TOKEN || envVal('SUPABASE_ACCESS_TOKEN')
const PASSWORD = process.env.SUPABASE_DB_PASSWORD || envVal('SUPABASE_DB_PASSWORD')

// ── Consultas de introspección: cada una devuelve una sola fila con la col `body` (texto DDL) ──
const SEP = (t) => `E'\\n\\n-- ============================================================\\n-- ${t}\\n-- ============================================================\\n'`

const Q_STRUCTURE = `
WITH s AS (SELECT (
  E'-- ============================================================\\n-- EXTENSIONES\\n-- ============================================================\\n'
  || COALESCE((SELECT string_agg(format('CREATE EXTENSION IF NOT EXISTS %I WITH SCHEMA %I;', extname, n.nspname), E'\\n' ORDER BY extname)
       FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace WHERE extname<>'plpgsql'), '')
  || ${SEP('TIPOS ENUM')}
  || COALESCE((SELECT string_agg(format('CREATE TYPE public.%I AS ENUM (%s);', t.typname, labels), E'\\n' ORDER BY t.typname)
       FROM (SELECT t.typname, t.oid, string_agg(quote_literal(e.enumlabel), ', ' ORDER BY e.enumsortorder) AS labels
             FROM pg_type t JOIN pg_enum e ON e.enumtypid=t.oid JOIN pg_namespace n ON n.oid=t.typnamespace
             WHERE n.nspname='public' GROUP BY t.typname, t.oid) t), '')
  || ${SEP('TABLAS')}
  || COALESCE((SELECT string_agg(ddl, E'\\n\\n' ORDER BY tbl) FROM (
       SELECT c.relname AS tbl,
         'CREATE TABLE public.' || quote_ident(c.relname) || E' (\\n' ||
         string_agg('  ' || quote_ident(a.attname) || ' ' || pg_catalog.format_type(a.atttypid,a.atttypmod)
           || CASE a.attidentity WHEN 'a' THEN ' GENERATED ALWAYS AS IDENTITY' WHEN 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY' ELSE '' END
           || CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END
           || CASE WHEN ad.adbin IS NOT NULL AND a.attidentity='' THEN ' DEFAULT ' || pg_get_expr(ad.adbin,ad.adrelid) ELSE '' END,
           E',\\n' ORDER BY a.attnum) || E'\\n);' AS ddl
       FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
       JOIN pg_attribute a ON a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped
       LEFT JOIN pg_attrdef ad ON ad.adrelid=c.oid AND ad.adnum=a.attnum
       WHERE n.nspname='public' AND c.relkind='r' GROUP BY c.relname) x), '')
  || ${SEP('CONSTRAINTS (PK / UNIQUE / CHECK / FK)')}
  || COALESCE((SELECT string_agg(format('ALTER TABLE public.%I ADD CONSTRAINT %I %s;', rel.relname, c.conname, pg_get_constraintdef(c.oid)), E'\\n' ORDER BY (c.contype='f'), rel.relname, c.conname)
       FROM pg_constraint c JOIN pg_class rel ON rel.oid=c.conrelid JOIN pg_namespace n ON n.oid=rel.relnamespace
       WHERE n.nspname='public' AND c.conrelid<>0), '')
  || ${SEP('ÍNDICES')}
  || COALESCE((SELECT string_agg(pg_get_indexdef(i.indexrelid)||';', E'\\n' ORDER BY c.relname, c.oid)
       FROM pg_index i JOIN pg_class c ON c.oid=i.indexrelid JOIN pg_namespace n ON n.oid=c.relnamespace
       WHERE n.nspname='public' AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid=i.indexrelid)), '')
) AS body) SELECT body FROM s`

const Q_FUNCTIONS = `
WITH s AS (SELECT (
  E'-- ============================================================\\n-- FUNCIONES\\n-- ============================================================\\n'
  || COALESCE((SELECT string_agg(pg_get_functiondef(p.oid), E'\\n\\n' ORDER BY p.proname)
       FROM pg_proc p WHERE p.pronamespace='public'::regnamespace AND p.prokind IN ('f','p')), '')
) AS body) SELECT body FROM s`

const Q_REST = `
WITH s AS (SELECT (
  E'-- ============================================================\\n-- TRIGGERS\\n-- ============================================================\\n'
  || COALESCE((SELECT string_agg(pg_get_triggerdef(t.oid)||';', E'\\n' ORDER BY c.relname, t.tgname)
       FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace
       WHERE n.nspname='public' AND NOT t.tgisinternal), '')
  || ${SEP('ROW LEVEL SECURITY')}
  || COALESCE((SELECT string_agg(format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', c.relname), E'\\n' ORDER BY c.relname)
       FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind='r' AND c.relrowsecurity), '')
  || ${SEP('POLICIES (RLS)')}
  || COALESCE((SELECT string_agg(
       format('CREATE POLICY %I ON public.%I AS %s FOR %s TO %s', policyname, tablename,
         CASE WHEN permissive='PERMISSIVE' THEN 'PERMISSIVE' ELSE 'RESTRICTIVE' END, cmd, array_to_string(roles, ', '))
       || COALESCE(E'\\n  USING (' || qual || ')', '') || COALESCE(E'\\n  WITH CHECK (' || with_check || ')', '') || ';',
       E'\\n' ORDER BY tablename, policyname)
       FROM pg_policies WHERE schemaname='public'), '')
  || ${SEP('GRANTS (tablas)')}
  || COALESCE((SELECT string_agg(format('GRANT %s ON public.%I TO %I;', privs, table_name, grantee), E'\\n' ORDER BY table_name, grantee)
       FROM (SELECT table_name, grantee, string_agg(privilege_type, ', ' ORDER BY privilege_type) AS privs
             FROM information_schema.role_table_grants
             WHERE table_schema='public' AND grantee IN ('anon','authenticated','service_role')
             GROUP BY table_name, grantee) g), '')
  || ${SEP('VISTAS')}
  || COALESCE((SELECT string_agg(format(E'CREATE OR REPLACE VIEW public.%I AS\\n%s', viewname, definition), E'\\n\\n' ORDER BY viewname)
       FROM pg_views WHERE schemaname='public'), '')
) AS body) SELECT body FROM s`

const Q_META = `SELECT (SELECT max(version) FROM supabase_migrations.schema_migrations) AS mig,
                (SELECT count(*)::int FROM pg_tables WHERE schemaname='public') AS tablas`

// ── Runners ──
async function runViaApi(queries) {
  const url = `https://api.supabase.com/v1/projects/${REF}/database/query`
  const one = async (query) => {
    const r = await fetch(url, {
      method: 'POST',
      headers: { Authorization: `Bearer ${TOKEN}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ query }),
    })
    if (!r.ok) throw new Error(`Management API ${r.status}: ${(await r.text()).slice(0, 300)}`)
    return r.json()
  }
  return Promise.all(queries.map(one))
}

async function runViaPg(queries) {
  let host = DIRECT ? `db.${REF}.supabase.co` : 'aws-1-sa-east-1.pooler.supabase.com'
  if (DIRECT) { const [ip6] = await resolve6(host); if (!ip6) throw new Error('sin AAAA'); host = ip6 }
  const client = new pg.Client({
    host, port: 5432, user: DIRECT ? 'postgres' : `postgres.${REF}`,
    password: PASSWORD, database: 'postgres', ssl: { rejectUnauthorized: false },
    application_name: 'g360-dump-schema',
  })
  await client.connect()
  try { return await Promise.all(queries.map(async (q) => (await client.query(q)).rows)) }
  finally { await client.end() }
}

async function main() {
  const queries = [Q_META, Q_STRUCTURE, Q_FUNCTIONS, Q_REST]
  const via = TOKEN ? 'API' : 'PG'
  if (!TOKEN && !PASSWORD) { console.error('Falta SUPABASE_ACCESS_TOKEN o SUPABASE_DB_PASSWORD.'); process.exit(1) }
  console.log(`Generando schema desde ${REF} vía ${via}...`)

  const [meta, structure, functions, rest] = (TOKEN ? await runViaApi(queries) : await runViaPg(queries))
  const { mig, tablas } = meta[0]
  const header =
`-- ============================================================
-- Genesis360 — Schema completo del esquema \`public\`
-- Generado ${new Date().toISOString()} desde ${REF} vía ${via}
-- Última migración aplicada: ${mig} · ${tablas} tablas
--
-- Reconstruido desde el catálogo de Postgres (NO es pg_dump byte-a-byte).
-- Regenerar:  npm run schema:dump   (ver cabecera de scripts/dump-schema.mjs)
-- ============================================================
`
  const text = [header, structure[0].body, functions[0].body, rest[0].body].join('\n') + '\n'
  writeFileSync(OUT, text.replace(/\r\n/g, '\n'), 'utf8')
  const n = (re) => (text.match(re) || []).length
  console.log(`OK → schema_full.sql (${(text.length/1024).toFixed(0)} KB · mig ${mig} · ${tablas} tablas)`)
  console.log(`   tablas=${n(/^CREATE TABLE /gm)} funcs=${n(/^CREATE (OR REPLACE )?FUNCTION /gm)} triggers=${n(/^CREATE (CONSTRAINT )?TRIGGER /gm)} policies=${n(/^CREATE POLICY /gm)} vistas=${n(/^CREATE OR REPLACE VIEW /gm)}`)
}

main().catch((e) => { console.error('ERROR:', e.message); process.exit(1) })
